### PR TITLE
Return output in `main` function in electrostatic and hydrophobic script

### PR DESCRIPTION
**Pull request by adam-kral**
Hey everyone,

I've made some updates to the `main()` functions in both the electrostatic and hydrophobic analysis scripts that I find useful (I hope others would too):

- `main()` functions in electrostatic and hydrophobic script now return the computed outputs.
- For the electrostatic analysis (`commandline_electrostatic.py:main`), it now returns integrals (which were only being printed to stdout before) and the vertices that belong to a patch. This is a bit more high-level than the surface (patches already assigned) while more detailed than patches.csv.

#### Advantages/Rationale
1. **Easier Processing**: Getting these outputs directly from `main()` makes downstream processing of the granular data in Python easy. And there is no need to modify `surface_analyses` code.
2. **Consistent, Detailed Data**: The hydrophobic script gives you detailed surface-level data, and now, so does the electrostatic script.

I tried to keep it simple, looking forward to hearing what you think!

### CODE REVIEW

**Comment by fwaibl** [comment]
Hi. Thanks for your pull request. I definitely agree with your rationale, it's a great idea to make scripting easier from the Python side. But I am not sure if it's a good idea to return stuff from main, since it might be mistaken for a return code.

We could move all of the "processing" from `main` into its own function, and leave the command line parsing in main. That way, the whole script would be usable with regular Python arguments and return its output like a proper function. And `main` could remain its own thing that takes no arguments, parses `sys.argv`, and returns `None` (or maybe 0 to indicate a successful run). Would that be a solution from your side? If yes, we could try to implement it some time this week.

Best,
Franz

**Comment by adam-kral** [comment]
Hi, thanks for the fast response!

Yes I see, the return value is indeed interpreted as the return code when used as "console_scripts" `in setup.py`.

Certain, that would be a great solution what you suggested. It would also be totally ok from my side, if the function, for simplicity, took just argv, or it took an argparse.Namespace (given you could obtain the parser and run it on your argv string).

**Comment by fwaibl** [comment]
I just added some code that provides a Python function with the functionality of commandline_electrostatic.py. @vhoer @adam-kral could you check if that is ok with you? I would still have to do the same in commandline_hydrophobic.py.

**Comment by adam-kral** [comment]
Thanks! That is perfect.

New users would however need to specify atom selection and stride when loading the trajectory with `load_aligned_trajectory` and could not rely on the default values as in the cli version provided by the defaults in the argparser, also given they are probably loading just a single structure, but this is for the power use(r) case anyway.

**Comment by fwaibl** [comment]
So I finally changed the hydrophobicity script. @adam-kral @vhoer could you check if the changes are ok with both of you?

**Comment by fwaibl** [comment]
> I changed one minor thing I added initially. `run_electrostatics` now returns in `patch_vertices` all vertices, not just those assigned a patch. (User can easily filter it with `.query(f'positive != -1 or negative != -1')` to get the previous result, but I now know I actually want all the vertices, and it's easier to just use the computed df directly than to compute the assignment again from returned `surf`.)

Yes, that makes sense. I also changed commandline_hydrophobic so that the `out` argument is not required anymore. This should be more reasonable when using the Python interface.

**Pull request merged**
